# -*- coding: utf-8 -*-
"""Task_Decode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeqc6wKokIGEzoiei5Q_Vav3GKp2C6X8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

#Load Dataset
df = pd.read_csv('/content/drive/MyDrive/Titanic-Dataset.csv')

#Explore Dataset Structure
df.head()        # first 5 rows
df.info()        # columns + data types
df.shape         # rows, columns
df.columns

#Understand Data
df.describe()

#TASK 2--- Data Cleaning & Preprocessing
#Missing Values
df.isnull().sum()

#Handle missing
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#remove duplicates
df.drop_duplicates(inplace=True)

#TASK 3--- Exploratory Data Analysis
#Basic Statistics
df.describe()

df.corr(numeric_only=True)

df['Survived'].value_counts()
df.groupby('Sex')['Survived'].mean()

#Detect Outliers
sns.boxplot(df['Fare'])
plt.show()

#TASK 4---- Data Visualization
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

sns.barplot(x='Sex', y='Survived', data=df)
plt.title("Survival Rate by Gender")
plt.show()

#heatmap
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

#TASK 5----Predictive Model
#spilt data
# Convert categorical → numeric
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

df = df.drop(['Name', 'Ticket', 'Cabin'], axis=1, errors='ignore')
print(df.columns)

#Survival by gender
df.groupby('Sex')['Survived'].mean()

#Survival by class
df.groupby('Pclass')['Survived'].mean()

#Correlation insight
df.corr(numeric_only=True)

#Split data
from sklearn.model_selection import train_test_split

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

